### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Enderborn1235** [Alex-BusNet/InfiniteStratos#1]
Is this repo still alive? If not, could I have permission to revive it?

**Comment by Alex-BusNet** [comment]
Is it alive? Yes, and no. I have been busy over the last year with school, once I graduate I plan to get the project back up. Sorry I took a year to respond, I didn't see that the issue was opened by someone else, I thought I put the issue there to remind myself later where I left off.

If you do want to clone this and make a pull request, you are more than welcome to. If you know anything regarding rendering objects, that would be most appreciated.
